#!/bin/bash

cd /var/log/auditshell
if [ "$?" != "0" ];then
   echo "ERROR: unable to enter dir /var/log/auditshell"
   exit 1
fi

#################################################################################
####
#### HELPERS

get_glob(){
   GLOB="????-??-??_??-??-??.$(whoami).*"
   for group in $(groups);
   do
      if [ "$group" = "auditshell" ];then
         GLOB="????-??-??_??-??-??.*.*"
      fi
   done
   if [ "$(whoami)" = "root" ];then
         GLOB="????-??-??_??-??-??.*.*"
   fi
   echo "$GLOB"
}

list_sessions(){
  for dir in $(get_glob);
  do
    if ( ! [ -d "$dir" ] );then
       continue
    fi 
    if ( ! ( ls -1 $NAME/timing.*  $NAME/typescript.* &>/dev/null ) );then
       echo "$dir"
    fi 
  done
}

show_session(){
     local NAME="$1"
     if ( ! (echo "$NAME"|grep -P "^[0-9a-zA-Z_\-][0-9a-zA-Z_\-\.]*$"));then
        echo "ERROR: NOT ALLOWED CHARACTERS"
        exit 1
     fi
     if ( ! ls -1 $(get_glob)|grep -q "$NAME" );then
        echo "ERROR: NOT ALLOWED, YOU ARE NOT MEMBER OF THE >>auditshell<< GROUP"
        exit 1
     fi
     if ( [ -f "$NAME/timing.${NAME}" ] && [ -f "$NAME/typescript.${NAME}" ] );then
        clear
        echo "STARTING REPLAY"
        scriptreplay -t "$NAME/timing.${NAME}"  "$NAME/typescript.${NAME}"
        echo "REPLAY COMPLETE"
     fi
}

#################################################################################
####
#### MAIN

ACTION="$1"
SESSION="$2"

case "$ACTION" in
  list)
        list_sessions
        ;;
  show)
        show_session "$SESSION"
        ;;
  *)
        echo "Usage: $0 {list|replay <session>}"
        exit 1
esac
