#!/bin/bash

#################################################################################
####
#### HELPERS

get_glob(){
   GLOB="????-??-??_??-??-??.$(whoami).*"
   for group in $(groups);
   do
      if [ "$group" = "auditshell" ];then
         GLOB="????-??-??_??-??-??.*.*"
      fi
   done
   if [ "$(whoami)" = "root" ];then
         GLOB="????-??-??_??-??-??.*.*"
   fi
   echo "$GLOB"
}

list_sessions(){
  shopt -s nullglob
  for dir in $(get_glob);
  do
    if ( ! [ -d "$dir" ] );then
       continue
    fi 
    if ( ls -1tr $NAME/timing.*  $NAME/typescript.* &>/dev/null );then
      lsof $NAME/typescript.* >/dev/null 2>&1
      RET="$?"
      if [ "$RET" = "0" ];then
         RUN_STATE="complete"
      else
         RUN_STATE="running"
      fi
      printf "%-45s %s\n" "$dir" "$RUN_STATE"
    fi 
  done
  shopt -u nullglob
}

show_session(){
     local NAME="$1"
   
     if [ "$AUDITSHELL" = "$NAME" ];then
        echo "ERROR: CANNOT SHOW A ALREADY RUNNING SESSION"
        exit 1
     fi

     shopt -s nullglob
     if ( ! ls -1 $(get_glob)|grep -q "$NAME" );then
        echo "ERROR: NOT ALLOWED, YOU ARE NOT MEMBER OF THE >>auditshell<< GROUP"
        exit 1
     fi
     shopt -u nullglob
     if ( [ -f "$NAME/timing.${NAME}" ] && [ -f "$NAME/typescript.${NAME}" ] );then
        clear
        echo "STARTING REPLAY"
        scriptreplay -t "$NAME/timing.${NAME}"  "$NAME/typescript.${NAME}"
        echo "REPLAY COMPLETE"
     fi
}

#################################################################################
####
#### MAIN

ACTION="$1"
SESSION="$2"

if ( ! (echo "$ACTION"|grep -q -P '^(list|show|)$'));then
   echo "ERROR: NOT ALLOWED PARAMETER"
   exit 1
fi


if ( ! (echo "$SESSION"|grep -q -P "^[0-9a-zA-Z_\-\.]*$"));then
   echo "ERROR: NOT ALLOWED CHARACTERS"
   exit 1
fi

cd /var/log/auditshell/sessions/
if [ "$?" != "0" ];then
   echo "ERROR: unable to enter dir /var/log/auditshell"
   exit 1
fi

case "$ACTION" in
  list)
        list_sessions
        ;;
  show)
        show_session "$SESSION"
        ;;
  *)
        echo "Usage: $0 {list|show <session>}"
        exit 1
esac
