#!/bin/bash

while read A;
do
   lsof "$A" >/dev/null 2>&1
   RET="$?"
   if [ "$RET" = "0" ];then
      gzip -6 --verbose "$A"
   fi
done <  <(find /var/log/auditshell/sessions -type f ! -name "*.gz")

